In [48]:
import pandas as pd
import numpy as np
import re

In [42]:
csv_file = "phrases.csv"
df = pd.read_csv(csv_file,encoding="utf-8")

In [50]:
pd.concat([df[col].astype(str).str.lower() for col in df.columns], axis=1)
df.head()

,words,wordCount,word1,word2,word3,word4,word5,word6,word7,word1_count,word2_count,word3_count,word4_count,word5_count,word6_count,word7_count
0,A Pile Of Coats,4,A,Pile,Of,Coats,None,None,None,1,4.0,2.0,5.0,NaN,NaN,NaN
1,A Pile Of Coats On The Bed,7,A,Pile,Of,Coats,On,The,Bed,1,4.0,2.0,5.0,2.0,3.0,3.0
2,A Shelf Full Of Knickknacks,5,A,Shelf,Full,Of,Knickknacks,None,None,1,5.0,4.0,2.0,11.0,NaN,NaN
3,A Sock With Holes In It,6,A,Sock,With,Holes,In,It,None,1,4.0,4.0,5.0,2.0,2.0,NaN
4,A Vase Filled With Sunflowers,5,A,Vase,Filled,With,Sunflowers,None,None,1,4.0,6.0,4.0,10.0,NaN,NaN

In [44]:
df['wordCount'] = [len(x.split()) for x in df['words'].tolist()]

In [45]:
df.wordCount.value_counts()

2    883
3    473
4    106
1     53
5     28
6     10
7      3
Name: wordCount, dtype: int64

In [46]:
df[['word1','word2','word3','word4','word5','word6','word7']] = df.words.str.split(" ",expand=True,)

In [47]:
df['word1_count']=df['word1'].str.len()
df['word2_count']=df['word2'].str.len()
df['word3_count']=df['word3'].str.len()
df['word4_count']=df['word4'].str.len()
df['word5_count']=df['word5'].str.len()
df['word6_count']=df['word6'].str.len()
df['word7_count']=df['word7'].str.len()

In [51]:
from collections import Counter

df1 = pd.DataFrame([Counter(list(x)) for x in df['words']], index=df.index)
order = list('abcdefghijklmnopqrstuvwxyz')

d = {'a': "count_a",
     'b': "count_b",
     'c':"count_c",
     'd':"count_d",
     'e':"count_e",
     'f':"count_f",
     'g':"count_g",
     'h':"count_h",
     'i':"count_i",
     'j':"count_j",
     'k':"count_k",
     'l':"count_l",
     'm':"count_m",
     'n':"count_n",
     'o':"count_o",
     'p':"count_p",
     'q':"count_q",
     'r':"count_r",
     's':"count_s",
     't':"count_t",
     'u':"count_u",
     'v':"count_v",
     'w':"count_w",
     'x':"count_x",
     'y':"count_y",
     'z':"count_z"
     }

df2 = df1.fillna(0).astype(int).reindex(columns=order, fill_value=0).rename(columns=d)
df = df.join(df2)

In [52]:
df.head()

,words,wordCount,word1,word2,word3,word4,word5,word6,word7,word1_count,...,count_q,count_r,count_s,count_t,count_u,count_v,count_w,count_x,count_y,count_z
0,A Pile Of Coats,4,A,Pile,Of,Coats,None,None,None,1,...,0,0,1,1,0,0,0,0,0,0
1,A Pile Of Coats On The Bed,7,A,Pile,Of,Coats,On,The,Bed,1,...,0,0,1,1,0,0,0,0,0,0
2,A Shelf Full Of Knickknacks,5,A,Shelf,Full,Of,Knickknacks,None,None,1,...,0,0,1,0,1,0,0,0,0,0
3,A Sock With Holes In It,6,A,Sock,With,Holes,In,It,None,1,...,0,0,1,2,0,0,0,0,0,0
4,A Vase Filled With Sunflowers,5,A,Vase,Filled,With,Sunflowers,None,None,1,...,0,1,2,1,1,0,1,0,0,0

In [53]:
phrase_data = df

In [55]:
phrase_data.columns

Index(['words', 'wordCount', 'word1', 'word2', 'word3', 'word4', 'word5',
       'word6', 'word7', 'word1_count', 'word2_count', 'word3_count',
       'word4_count', 'word5_count', 'word6_count', 'word7_count', 'count_a',
       'count_b', 'count_c', 'count_d', 'count_e', 'count_f', 'count_g',
       'count_h', 'count_i', 'count_j', 'count_k', 'count_l', 'count_m',
       'count_n', 'count_o', 'count_p', 'count_q', 'count_r', 'count_s',
       'count_t', 'count_u', 'count_v', 'count_w', 'count_x', 'count_y',
       'count_z'],
      dtype='object')

In [64]:
phrase_data=phrase_data.drop(columns=['word1','word2','word3','word4','word5','word6','word7'])

In [65]:
final_data= phrase_data.fillna(0)

In [66]:
final_data.head()

,words,wordCount,word1_count,word2_count,word3_count,word4_count,word5_count,word6_count,word7_count,count_a,...,count_q,count_r,count_s,count_t,count_u,count_v,count_w,count_x,count_y,count_z
0,A Pile Of Coats,4,1,4.0,2.0,5.0,0.0,0.0,0.0,1,...,0,0,1,1,0,0,0,0,0,0
1,A Pile Of Coats On The Bed,7,1,4.0,2.0,5.0,2.0,3.0,3.0,1,...,0,0,1,1,0,0,0,0,0,0
2,A Shelf Full Of Knickknacks,5,1,5.0,4.0,2.0,11.0,0.0,0.0,1,...,0,0,1,0,1,0,0,0,0,0
3,A Sock With Holes In It,6,1,4.0,4.0,5.0,2.0,2.0,0.0,0,...,0,0,1,2,0,0,0,0,0,0
4,A Vase Filled With Sunflowers,5,1,4.0,6.0,4.0,10.0,0.0,0.0,1,...,0,1,2,1,1,0,1,0,0,0

In [63]:
final_data

,words,wordCount,word1_count,word2_count,word3_count,word4_count,word5_count,word6_count,word7_count,count_a,...,count_q,count_r,count_s,count_t,count_u,count_v,count_w,count_x,count_y,count_z
0,A Pile Of Coats,4,1,4.0,2.0,5.0,NaN,NaN,NaN,1,...,0,0,1,1,0,0,0,0,0,0
1,A Pile Of Coats On The Bed,7,1,4.0,2.0,5.0,2.0,3.0,3.0,1,...,0,0,1,1,0,0,0,0,0,0
2,A Shelf Full Of Knickknacks,5,1,5.0,4.0,2.0,11.0,NaN,NaN,1,...,0,0,1,0,1,0,0,0,0,0
3,A Sock With Holes In It,6,1,4.0,4.0,5.0,2.0,2.0,NaN,0,...,0,0,1,2,0,0,0,0,0,0
4,A Vase Filled With Sunflowers,5,1,4.0,6.0,4.0,10.0,NaN,NaN,1,...,0,1,2,1,1,0,1,0,0,0
5,A Vase Of Flowers,4,1,4.0,2.0,7.0,NaN,NaN,NaN,1,...,0,1,2,0,0,0,1,0,0,0
6,A Vase Of Fresh Cut Garden Flowers,7,1,4.0,2.0,5.0,3.0,6.0,7.0,2,...,0,3,3,1,1,0,1,0,0,0
7,Accent Cabinet,2,6,7.0,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,2,0,0,0,0,0,0
8,Accent Furniture,2,6,9.0,NaN,NaN,NaN,NaN,NaN,0,...,0,2,0,2,2,0,0,0,0,0
9,Accent Window,2,6,6.0,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,1,0,0,1,0,0,0
10,Address Book,2,7,4.0,NaN,NaN,NaN,NaN,NaN,0,...,0,1,2,0,0,0,0,0,0,0
11,Address Labels,2,7,6.0,NaN,NaN,NaN,NaN,NaN,1,...,0,1,3,0,0,0,0,0,0,0
12,Adjustable Shoe Rack,3,10,4.0,4.0,NaN,NaN,NaN,NaN,2,...,0,0,1,1,1,0,0,0,0,0
13,Adjustable Swivel Stool,3,10,6.0,5.0,NaN,NaN,NaN,NaN,1,...,0,0,1,2,1,1,1,0,0,0
14,Afghan Rug,2,6,3.0,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,0,1,0,0,0,0,0
15,After-Shave Lotion,2,11,6.0,NaN,NaN,NaN,NaN,NaN,1,...,0,1,0,2,0,1,0,0,0,0
16,Air Conditioning,2,3,12.0,NaN,NaN,NaN,NaN,NaN,0,...,0,1,0,1,0,0,0,0,0,0
17,Air Freshener,2,3,9.0,NaN,NaN,NaN,NaN,NaN,0,...,0,3,1,0,0,0,0,0,0,0
18,Air Mattress,2,3,8.0,NaN,NaN,NaN,NaN,NaN,1,...,0,2,2,2,0,0,0,0,0,0
19,Alarm Clock,2,5,5.0,NaN,NaN,NaN,NaN,NaN,1,...,0,1,0,0,0,0,0,0,0,0
20,Alarm Clock With Nature Sounds,5,5,5.0,4.0,6.0,6.0,NaN,NaN,2,...,0,2,1,2,2,0,0,0,0,0
21,All-In-One Home Gym,3,10,4.0,3.0,NaN,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0,0,1,0
22,All-Purpose Cleaners,2,11,8.0,NaN,NaN,NaN,NaN,NaN,1,...,0,2,2,0,1,0,0,0,0,0
23,Aloe-Vera Hand Soap,3,9,4.0,4.0,NaN,NaN,NaN,NaN,3,...,0,1,0,0,0,0,0,0,0,0
24,Amusing Yarn,2,7,4.0,NaN,NaN,NaN,NaN,NaN,1,...,0,1,1,0,1,0,0,0,0,0
25,An Air Conditioner Running Full Blast,6,2,3.0,11.0,7.0,4.0,5.0,NaN,1,...,0,2,1,2,2,0,0,0,0,0
26,Angle Broom With Dustpan,4,5,5.0,4.0,7.0,NaN,NaN,NaN,1,...,0,1,1,2,1,0,0,0,0,0
27,Angora Sweater,2,6,7.0,NaN,NaN,NaN,NaN,NaN,2,...,0,2,0,1,0,0,1,0,0,0
28,Animal-Shaped Lamps,2,13,5.0,NaN,NaN,NaN,NaN,NaN,3,...,0,0,1,0,0,0,0,0,0,0
29,Annual Sailing Weekend Event,4,6,7.0,7.0,5.0,NaN,NaN,NaN,2,...,0,0,0,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1526,Wooden Door,2,6,4.0,NaN,NaN,NaN,NaN,NaN,0,...,0,1,0,0,0,0,0,0,0,0
1527,Wooden Double Doors,3,6,6.0,5.0,NaN,NaN,NaN,NaN,0,...,0,1,1,0,1,0,0,0,0,0
1528,Wooden End Table,3,6,3.0,5.0,NaN,NaN,NaN,NaN,1,...,0,0,0,0,0,0,0,0,0,0
1529,Wooden Incense Burner,3,6,7.0,6.0,NaN,NaN,NaN,NaN,0,...,0,2,1,0,1,0,0,0,0,0
1530,Wooden Shelf,2,6,5.0,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,0,0,0,0,0,0,0
1531,Wooden Shutters,2,6,8.0,NaN,NaN,NaN,NaN,NaN,0,...,0,1,1,2,1,0,0,0,0,0
1532,Wooden Stepladder,2,6,10.0,NaN,NaN,NaN,NaN,NaN,1,...,0,1,0,1,0,0,0,0,0,0
1533,Wooden Table,2,6,5.0,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,0,0,0,0,0,0,0
1534,Wood-Grained Paneling,2,12,8.0,NaN,NaN,NaN,NaN,NaN,2,...,0,1,0,0,0,0,0,0,0,0
1535,Wood-Paneled Ceiling,2,12,7.0,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,0,0,0,0,0,0,0
1536,Wool Blazer,2,4,6.0,NaN,NaN,NaN,NaN,NaN,1,...,0,1,0,0,0,0,0,0,0,1
1537,Wool Pajamas,2,4,7.0,NaN,NaN,NaN,NaN,NaN,3,...,0,0,1,0,0,0,0,0,0,0
1538,Wool Shag Rug,3,4,4.0,3.0,NaN,NaN,NaN,NaN,1,...,0,0,0,0,1,0,0,0,0,0
1539,Wool Sweater,2,4,7.0,NaN,NaN,NaN,NaN,NaN,1,...,0,1,0,1,0,0,1,0,0,0
1540,Wool V-Neck Sweater,3,4,6.0,7.0,NaN,NaN,NaN,NaN,1,...,0,1,0,1,0,0,1,0,0,0
1541,Wool Zip Cardigan Sweater,4,4,3.0,8.0,7.0,NaN,NaN,NaN,3,...,0,2,0,1,0,0,1,0,0,0
1542,Workbench Table,2,9,5.0,NaN,NaN,NaN,NaN,NaN,1,...,0,1,0,0,0,0,0,0,0,0
1543,Working Fireplace,2,7,9.0,NaN,NaN,NaN,NaN,NaN,1,...,0,2,0,0,0,0,0,0,0,0
1544,Worn Rug,2,4,3.0,NaN,NaN,NaN,NaN,NaN,0,...,0,1,0,0,1,0,0,0,0,0
1545,Worn Sneakers,2,4,8.0,NaN,NaN,NaN,NaN,NaN,1,...,0,2,1,0,0,0,0,0,0,0
1546,Woven Horse Blanket,3,5,5.0,7.0,NaN,NaN,NaN,NaN,1,...,0,1,1,1,0,1,0,0,0,0
1547,Woven Pillow Covers,3,5,6.0,6.0,NaN,NaN,NaN,NaN,0,...,0,1,1,0,0,2,1,0,0,0
1548,Woven Place Mats,3,5,5.0,4.0,NaN,NaN,NaN,NaN,2,...,0,0,1,1,0,1,0,0,0,0
1549,Woven Placemats,2,5,9.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,1,1,0,1,0,0,0,0
1550,Woven Placements,2,5,10.0,NaN,NaN,NaN,NaN,NaN,1,...,0,0,1,1,0,1,0,0,0,0
1551,Wraparound Window Seat,3,10,6.0,4.0,NaN,NaN,NaN,NaN,3,...,0,2,0,1,1,0,1,0,0,0
1552,Writing A Love Letter,4,7,1.0,4.0,6.0,NaN,NaN,NaN,0,...,0,2,0,3,0,1,0,0,0,0
1553,Writing Tablet,2,7,6.0,NaN,NaN,NaN,NaN,NaN,1,...,0,1,0,2,0,0,0,0,0,0
1554,Wrought-Iron Chandeliers,2,12,11.0,NaN,NaN,NaN,NaN,NaN,1,...,0,3,1,1,1,0,0,0,0,0
1555,Yellow Sundress,2,6,8.0,NaN,NaN,NaN,NaN,NaN,0,...,0,1,2,0,1,0,1,0,0,0